name = "ExpectationMaximization"
uuid = "e1fe09cc-5134-44c2-a941-50f4cd97986a"
authors = ["David MÃ©tivier <david.metivier@inrae.fr> and contributors"]
version = "0.2.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArgCheck = "2"
Distributions = "0.24, 0.25"
LogExpFunctions = "0.3"
StatsBase = "0.33, 0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
